### ISSUE TITLE
Find Security Bugs 1.2.1 released

### ISSUE THREAD

**Issue by h3xstream** [porscheinformatik/sonar-find-sec-bugs-plugin#9]
Hi guys !
I have release a new version of the plugin (1.2.1). Many rules were added.
Thanks to a new contributor the description had important updates (grammar and technical details). Most/All of the rules were updated. [New rules](http://h3xstream.github.io/find-sec-bugs/bugs.htm)

Also, I was wondering if the [`rules.xml`](https://github.com/porscheinformatik/sonar-find-sec-bugs-plugin/blob/master/src/main/resources/org/sonar/plugins/findsecbugs/rules.xml) was generated automatically. Maybe, a Python/Groovy script could be done..

**Comment by derkoe** [comment]
Find-Security-Bugs is now included in [SonarQube's own FindBugs Pluign](http://docs.sonarqube.org/display/PLUG/FindBugs+Plugin). Therefore I will close this project.

**Comment by h3xstream** [comment]
@derkoe Thanks for maintaining a sonar plugin and starting the initiative !
